name: flutter_bluetooth_basic
description: Flutter plugin that allows to find bluetooth devices & send raw bytes data
version: 2.0.1
homepage: https://github.com/andrey-ushakov/flutter_bluetooth_basic

environment:
  sdk: ">=2.12.2 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.4.0
  json_serializable: ^6.1.4
  permission_handler: ^9.0.1
  rxdart: ^0.27.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7

flutter:
  plugin:
    platforms:
      android:
        package: com.tablemi.flutter_bluetooth_basic
        pluginClass: FlutterBluetoothBasicPlugin
      ios:
        pluginClass: FlutterBluetoothBasicPlugin
